name: Continuous Delivery

on:
  push:
    branches: [main]

env:
  NODE_VERSION: "18.x"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/reservoirprotocol/datadog-agent:latest
            ghcr.io/reservoirprotocol/datadog-agent:${{ github.sha }}

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build]
    environment: dev
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    steps:
      - name: Checkout repository k8s-configs
        uses: actions/checkout@v3
        with:
          repository: unevenlabs/k8s-configs
          token: ${{ secrets.DEVOPSBOT_TOKEN }}
          path: k8s-configs

      - name: Deploy to Dev Environment
        working-directory: k8s-configs
        run: |
          ./utils/version_update.sh \
            ./dev/infrastructure/datadog-agent.yaml \
            ${{ github.sha }} \
            datadog-agent

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build]
    environment: prod
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    steps:
      - name: Checkout repository k8s-configs
        uses: actions/checkout@v3
        with:
          repository: unevenlabs/k8s-configs
          token: ${{ secrets.DEVOPSBOT_TOKEN }}
          path: k8s-configs

      - name: Deploy to Prod Environment
        working-directory: k8s-configs
        run: |
          ./utils/version_update.sh \
            ./prod/infrastructure/datadog-agent.yaml \
            ${{ github.sha }} \
            datadog-agent
